sources:
  - name: clober-v2
    handler:
      graphql:
        endpoint: '{context.url:https://subgraph.satsuma-prod.com/f6a8c4889b7b/clober/v2-core-subgraph/api}'

documents:
  - ./apis/**/*.graphql


codegen:
  contextType: 'MeshContext & { url: string }'
